backend:
  name: git-gateway
  # change repo to your git repository url
  repo: favina/gatsby-starter-delog

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
  - name: homepage
    label: Homepage
    preview_path: /
    files:
      - name: HomepageBanner
        label: HomepageBanner
        file: site-meta-data.json
        fields:
          - name: menuItems
            widget: list
            label: Menu Items
            required: true
            fields:
              - { label: Menu Item, name: menuItem, widget: string }
          - name: homeBannerContent
            widget: object
            label: Homepage Banner Content
            fields:
              - name: title
                widget: string
                label: Title
                required: true
              - name: description
                widget: string
                label: Description
                required: false
              - name: image
                widget: image
                label: Featured Image
                required: true
                media_library:
                  config:
                    multiple: false
              - name: bannerButtonText
                widget: string
                label: Banner Button Text
                required: false
              - name: bannerbuttonLink
                widget: string
                label: Banner Button Link
                required: false
  - name: homepageContent
    label: HomepageContent
    files:
      - name: about
        label: About
        file: site-about-data.json
        fields:
          - label: About
            name: about
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - label: SubText
                name: subtext
                widget: markdown
              - name: table
                label: Table
                widget: object
                required: false
                fields:
                  - label: Heading
                    name: heading
                    widget: list
                    required: false
                    fields:
                      - { name: title, label: Title, widget: string }
                  - label: Column
                    name: column
                    widget: list
                    required: false
                    fields:
                      - name: ColumnData
                        label: column Data
                        widget: list
                        fields:
                          - name: Row
                            label: row
                            widget: list
                            fields:
                              - { name: Data, label: Data, widget: string }
              - label: Text
                name: text
                widget: markdown
      - name: KeyDates
        label: Key Dates
        file: site-keyDates-data.json
        fields:
          - label: Key Dates
            name: keyDates
            widget: object
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - label: Text
                name: text
                widget: markdown
      - name: conferenceTopics
        label: Conference topics
        file: site-ConferenceTopics-data.json
        fields:
          - label: Conference topics
            name: conferenceTopics
            widget: object
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - label: Text
                name: text
                widget: markdown
      - name: Committee
        label: committee
        file: site-committee-data.json
        fields:
          - label: Committee
            name: committee
            widget: object
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - label: SubText
                name: subtext
                widget: text
              - label: ProfileData
                name: profileData
                widget: list
                required: false
                fields:
                  - name: image
                    label: image
                    widget: image
                  - name: title
                    label: Title
                    widget: string
                  - name: text
                    label: Text
                    widget: text
              - label: Text
                name: text
                widget: markdown
      - name: Speakers
        label: speakers
        file: site-speakers-data.json
        fields:
          - name: title
            label: Title
            widget: string
          - label: SubText
            name: subtext
            widget: text
          - label: Speaker Details
            name: profileData
            widget: list
            required: false
            fields:
              - name: image
                label: image
                widget: image
              - name: title
                label: Title
                widget: string
              - name: text
                label: text
                widget: text
          - label: Text
            name: text
            widget: markdown
      - name: Submissions
        label: submissions
        file: site-submissions-data.json
        fields:
          - label: Submission
            name: submissions
            widget: object
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - label: Text
                name: text
                widget: markdown
      - name: Partners
        label: partners
        file: site-partners-data.json
        fields:
          - label: Partners
            name: partners
            widget: list
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - label: Text
                name: text
                widget: markdown
      - name: Site Footer
        label: siteFooter
        file: site-footer-data.json
        fields:
          - label: Site Footer
            name: siteFooter
            widget: object
            required: false
            fields:
              - name: title
                label: Title
                widget: string
              - name: columnOneTitle
                label: Column one title
                widget: string
              - label: Column one Text
                name: columnOneText
                widget: text
              - name: columnTwoTitle
                label: Column two title
                widget: string
              - label: columnTwoText
                name: Column Two text
                widget: text
              - name: columnThreeTitle
                label: Column Three title
                widget: string
              - label: columnThreeText
                name: Column three text
                widget: text
